export const products = [
  // Chairs
  {
    id: 1,
    name: "Comfortable Chair",
    category: "Chair",
    price: 99,
    imageUrl: "chair-1.png",
    rating: 5,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 2,
    name: "Ergonomic Chair",
    category: "Chair",
    price: 129,
    imageUrl: "chair-2.png",
    rating: 4,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 3,
    name: "Stylish Armchair",
    category: "Chair",
    price: 149,
    imageUrl: "chair-3.png",
    rating: 3,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 4,
    name: "Leather Recliner",
    category: "Chair",
    price: 199,
    imageUrl: "chair-4.png",
    rating: 4,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 5,
    name: "Minimalist Chair",
    category: "Chair",
    price: 89,
    imageUrl: "chair-5.png",
    rating: 4.5,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },

  // Beds
  {
    id: 6,
    name: "King Size Bed",
    category: "Beds",
    price: 299,
    imageUrl: "beds-1.png",
    rating: 5,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 7,
    name: "Queen Size Bed",
    category: "Beds",
    price: 249,
    imageUrl: "beds-2.png",
    rating: 5,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 8,
    name: "Modern Bed Frame",
    category: "Beds",
    price: 399,
    imageUrl: "beds-3.png",
    rating: 3,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 9,
    name: "Platform Bed",
    category: "Beds",
    price: 349,
    imageUrl: "beds-4.png",
    rating: 2,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 10,
    name: "Sleigh Bed",
    category: "Beds",
    price: 459,
    imageUrl: "beds-5.png",
    rating: 5,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },

  // Sofas
  {
    id: 11,
    name: "Luxury Sofa",
    category: "Sofa",
    price: 499,
    imageUrl: "sofa-1.png",
    rating: 4,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 12,
    name: "Compact Sofa",
    category: "Sofa",
    price: 399,
    imageUrl: "sofa-2.png",
    rating: 5,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 13,
    name: "L-shaped Sofa",
    category: "Sofa",
    price: 699,
    imageUrl: "sofa-3.png",
    rating: 4,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 14,
    name: "Sofa with Chaise",
    category: "Sofa",
    price: 549,
    imageUrl: "sofa-4.png",
    rating: 5,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 15,
    name: "Sectional Sofa",
    category: "Sofa",
    price: 799,
    imageUrl: "sofa-5.png",
    rating: 3.6,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },

  // Lamps
  {
    id: 16,
    name: "Modern Lamp",
    category: "Lamp",
    price: 49,
    imageUrl: "lamp-1.png",
    rating: 5,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 17,
    name: "Classic Lamp",
    category: "Lamp",
    price: 59,
    imageUrl: "lamp-2.png",
    rating: 4,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 18,
    name: "Wooden Table Lamp",
    category: "Lamp",
    price: 69,
    imageUrl: "lamp-3.png",
    rating: 3,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 19,
    name: "Industrial Floor Lamp",
    category: "Lamp",
    price: 89,
    imageUrl: "lamp-4.png",
    rating: 5,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 20,
    name: "Vintage Desk Lamp",
    category: "Lamp",
    price: 79,
    imageUrl: "lamp-6.png",
    rating: 4,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 21,
    name: "Comfortable Chair-Table",
    category: "New-Arrival",
    price: 129,
    imageUrl: "newchair(1).png",
    rating: 5,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 22,
    name: "Comfortable Bed",
    category: "New-Arrival",
    price: 429,
    imageUrl: "newbed(2).png",
    rating: 4,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 23,
    name: "Comfortable Bed",
    category: "New-Arrival",
    price: 349,
    imageUrl: "newbed(3).png",
    rating: 3,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 24,
    name: "Comfortable Chair",
    category: "New-Arrival",
    price: 89,
    imageUrl: "newdaining(4).png",
    rating: 4,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 25,
    name: "Daining Table Chair",
    category: "New-Arrival",
    price: 189,
    imageUrl: "newdaining(5).png",
    rating: 4.5,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },

  // Beds
  {
    id: 26,
    name: "King Sofa",
    category: "New-Arrival",
    price: 399,
    imageUrl: "newsofa(6).png",
    rating: 5,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 27,
    name: "Daining Table",
    category: "New-Arrival",
    price: 249,
    imageUrl: "newdaining(7).png",
    rating: 5,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 28,
    name: "Daining Table",
    category: "New-Arrival",
    price: 299,
    imageUrl: "newdaining(8).png",
    rating: 3,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 29,
    name: "Platform Bed",
    category: "New-Arrival",
    price: 349,
    imageUrl: "newbed(9).png",
    rating: 2,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 30,
    name: "King Almira",
    category: "New-Arrival",
    price: 459,
    imageUrl: "newalmira(10).png",
    rating: 5,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },

  // Sofas
  {
    id: 31,
    name: "Luxury Bed",
    category: "New-Arrival",
    price: 499,
    imageUrl: "newbed(11).png",
    rating: 4,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 32,
    name: "Super Rak",
    category: "New-Arrival",
    price: 199,
    imageUrl: "newrak(12).png",
    rating: 5,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 33,
    name: "Luxury WalRak",
    category: "New-Arrival",
    price: 399,
    imageUrl: "newwalral(13).png",
    rating: 4,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 34,
    name: "Best Rak",
    category: "New-Arrival",
    price: 49,
    imageUrl: "newrak(14).png",
    rating: 5,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 35,
    name: "Super Lamp",
    category: "New-Arrival",
    price: 79,
    imageUrl: "newlamp1.png",
    rating: 5,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 36,
    name: "Best Lamp",
    category: "New-Arrival",
    price: 79,
    imageUrl: "newlamp2.png",
    rating: 4,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 37,
    name: "Stylish Lamp",
    category: "New-Arrival",
    price: 69,
    imageUrl: "newlamp3.png",
    rating: 3,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 38,
    name: "Luxury Lamp",
    category: "New-Arrival",
    price: 59,
    imageUrl: "newlamp4.png",
    rating: 4,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 39,
    name: "Best Lamp",
    category: "New-Arrival",
    price: 49,
    imageUrl: "newlamp5.png",
    rating: 4.5,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },

  // Beds
  {
    id: 40,
    name: "Luxury Lamp",
    category: "New-Arrival",
    price: 99,
    imageUrl: "newlamp6.png",
    rating: 5,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 41,
    name: "Super Lamp",
    category: "New-Arrival",
    price: 79,
    imageUrl: "newlamp7.png",
    rating: 5,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
];