export const products = [
  // Chairs
  {
    id: 1,
    name: "Comfortable Chair",
    category: "Chair",
    price: 99,
    imageUrl: "chair-1.png",
    rating: 5,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 2,
    name: "Ergonomic Chair",
    category: "Chair",
    price: 129,
    imageUrl: "chair-2.png",
    rating: 4,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 3,
    name: "Stylish Armchair",
    category: "Chair",
    price: 149,
    imageUrl: "chair-3.png",
    rating: 3,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 4,
    name: "Leather Recliner",
    category: "Chair",
    price: 199,
    imageUrl: "chair-4.png",
    rating: 4,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 5,
    name: "Minimalist Chair",
    category: "Chair",
    price: 89,
    imageUrl: "chair-5.png",
    rating: 4.5,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },

  // Beds
  {
    id: 6,
    name: "King Size Bed",
    category: "Beds",
    price: 299,
    imageUrl: "beds-1.png",
    rating: 5,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 7,
    name: "Queen Size Bed",
    category: "Beds",
    price: 249,
    imageUrl: "beds-2.png",
    rating: 5,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 8,
    name: "Modern Bed Frame",
    category: "Beds",
    price: 399,
    imageUrl: "beds-3.png",
    rating: 3,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 9,
    name: "Platform Bed",
    category: "Beds",
    price: 349,
    imageUrl: "beds-4.png",
    rating: 2,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 10,
    name: "Sleigh Bed",
    category: "Beds",
    price: 459,
    imageUrl: "beds-5.png",
    rating: 5,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },

  // Sofas
  {
    id: 11,
    name: "Luxury Sofa",
    category: "Sofa",
    price: 499,
    imageUrl: "sofa-1.png",
    rating: 4,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 12,
    name: "Compact Sofa",
    category: "Sofa",
    price: 399,
    imageUrl: "sofa-2.png",
    rating: 5,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 13,
    name: "L-shaped Sofa",
    category: "Sofa",
    price: 699,
    imageUrl: "sofa-3.png",
    rating: 4,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 14,
    name: "Sofa with Chaise",
    category: "Sofa",
    price: 549,
    imageUrl: "sofa-4.png",
    rating: 5,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 15,
    name: "Sectional Sofa",
    category: "Sofa",
    price: 799,
    imageUrl: "sofa-5.png",
    rating: 3.6,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },

  // Lamps
  {
    id: 16,
    name: "Modern Lamp",
    category: "Lamp",
    price: 49,
    imageUrl: "lamp-1.png",
    rating: 5,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 17,
    name: "Classic Lamp",
    category: "Lamp",
    price: 59,
    imageUrl: "lamp-2.png",
    rating: 4,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 18,
    name: "Wooden Table Lamp",
    category: "Lamp",
    price: 69,
    imageUrl: "lamp-3.png",
    rating: 3,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 19,
    name: "Industrial Floor Lamp",
    category: "Lamp",
    price: 89,
    imageUrl: "lamp-4.png",
    rating: 5,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
  {
    id: 20,
    name: "Vintage Desk Lamp",
    category: "Lamp",
    price: 79,
    imageUrl: "lamp-6.png",
    rating: 4,
    Description: "At Raj Furniture is offering get the worlds best and most famous products for your home/office. Customer preference is our main goal. We are always committed to providing the best quality furniture.",
  },
];